#!/bin/sh
cat  << EOF > $1.html
<html>
<head>
  <meta charset="UTF-8">
  <script language="javascript" type="text/javascript" src="p5/p5.js"></script>
  <!-- uncomment lines below to include extra p5 p5 -->
  <!--<script language="javascript" src="p5/p5.sound.js"></script>-->
  <script language="javascript" type="text/javascript" src="$1.js"></script>
  <!-- this line removes any default padding and style. you might only need one of these values set. -->
  <style> body {padding: 0; margin: 0;} </style>
</head>

<body>
</body>
</html>
EOF
cat << EOF > $1.js
function setup() {

}
function draw() {

}
EOF
